version: "3"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: ./server/.env
    image: "kartonowy/booknookserver:1.0"
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - backend
    image: "kartonowy/booknookclient:1.0"
